# Starship Configuration
# Tokyo Night theme with custom modules for Python, Battery, and more

# Increase command timeout to prevent timeout warnings
command_timeout = 1000  # milliseconds (default is 500)

# Format string - defines the prompt layout
# Added: $python (for version + virtual env) and $battery
format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_commit\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
$nodejs\
$terraform\
$aws\
[](fg:#212736 bg:#1d2230)\
$battery\
$time\
[ ](fg:#1d2230)\
\n$character"""

# Directory - shows current path
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 16
truncation_symbol = "…/"

# Smart directory name substitutions with icons
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = "󰧨 "
"Projects" = " "
"Code" = " "

# Git branch - shows current branch name
[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

# Git status - shows repo status (changes, ahead/behind, etc.)
[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# Git commit - Shows current commit hash:
[git_commit]
symbol = " "
format = "[[$tag$hash]($style) ]($style)"
style = "bg:#394260"
only_detached = true

# Python - shows version and virtual environment
[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) (\($virtualenv\) )](fg:#769ff0 bg:#212736)]($style)'
pyenv_version_name = false
python_binary = ["python3", "python"]  # Try python3 first
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "pyproject.toml", "requirements.txt", "setup.py", "setup.cfg"]
detect_folders = []

# Node.js
[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'


# Battery - shows battery level and charging status
[battery]
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"
unknown_symbol = "󰁽"
empty_symbol = "󰂎"
format = "[[ $symbol $percentage ](fg:#a0a9cb bg:#1d2230)]($style)"

[[battery.display]]
threshold = 10
style = "fg:#f7768e bg:#1d2230"  # Red when low

[[battery.display]]
threshold = 30
style = "fg:#e0af68 bg:#1d2230"  # Yellow when medium

[[battery.display]]
threshold = 100
style = "fg:#9ece6a bg:#1d2230"  # Green when good

# Time - shows current time
[time]
disabled = false
time_format = "%R"  # Hour:Minute Format (24h)
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

# Character - the prompt symbol
[character]
success_symbol = "[❯](bold fg:#9ece6a)"
error_symbol = "[❯](bold fg:#f7768e)"
vimcmd_symbol = "[❮](bold fg:#9ece6a)"

# Optional: Add more language support as needed
# Uncomment and customize these if you use them

# # Rust
# [rust]
# symbol = " "
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# # Go
# [golang]
# symbol = " "
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# # PHP
# [php]
# symbol = ""
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# [docker_context]
# symbol = " "
# style = "bg:#212736"
# format = '[[ $symbol $context ](fg:#769ff0 bg:#212736)]($style)'

# [java]
# symbol = " "
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# [ruby]
# symbol = " "
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:#212736"
format = '[[ $symbol $version ](fg:#769ff0 bg:#212736)]($style)'

[aws]
symbol = " "
format = "[[ $symbol $profile ](fg:#e0af68 bg:#212736)]($style)"
style = "bg:#212736"

# [kubernetes]
# symbol = "󱃾 "
# style = "bg:#212736"
# format = '[[ $symbol $context ](fg:#769ff0 bg:#212736)]($style)'
# disabled = false
